### PR TITLE
Get subarray corners in mirage format from pysiaf

### PR DESCRIPTION
**Pull request by Johannes-Sahlmann**
Add pysiaf dependence and provide function to get subarray corners in mirage format from SIAF directly.

Add unit test.

### CODE REVIEW

**Comment by bhilbert4** [comment]
When I try this out, it seems like the coordinates that it returns are too low by 1 for the starting x and y values. For example, full frame apertures have returned coordinates of [-1, 2047]. And NRCA1_SUB160 has [1887, 2047], when it should be [1888, 2047].

**Comment by Johannes-Sahlmann** [comment]
Yes, that is what we were discussing yesterday. My idea was that you would merge this PR and then tweak `sci_subarray_corners` to suit the needs of mirage. What do you think?

**Comment by bhilbert4** [comment]
Thinking a little more about this...I think different values need to be subtracted from the starting and ending indexes. 

For example, assume SIAF returns a value of (100.5, 100.5) for the starting position of the subarray. This is the left/bottom edge of pixel (101, 101), right? So for our purposes, we need to add 0.5 to get to (101, 101), but then subtract 1 to get from 1-indexed to 0-indexed values. So in total we need to subtract 0.5.

For the ending position of the subarray, assume SIAF returns (150.5, 150.5). This corresponds to the right edge of pixel (150, 150), right? This time we need to subtract 0.5 to get to the center of this pixel at the edge of the subarray. We also need to subtract 1 to get from 1-indexed to 0-indexed values. So here we need to subtract 1.5.

Does that sound correct?

**Comment by bhilbert4** [comment]
Ah yes. Sounds good. I can merge and integrate this with the other pysiaf-related changes I've made.

**Pull request merged**
